site_name: HCMS Documentation
site_url: https://sushantjillawar24.github.io/cmsinfo/
theme:
  name: material
  features:
    - navigation.instant
  palette:
    primary: 'indigo'
    accent: 'indigo'
  hide:
    - navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Platform: platform.md
  - Cost Optimization: cost-optimization.md
  - DevOps and Support: devops-support.md
  - Security and Compliance: security-compliance.md
  - Announcements: announcements.md
