site_name: Documentation
site_url: https://sushantjillawar24.github.io/cmsinfo/
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Platform: platform.md
  - Cost Optimization: cost-optimization.md
  - DevOps and Support: devops-support.md
  - Security and Compliance: security-compliance.md
  - Announcements: announcements.md
